version: '3'

services:
  redis:
    image: redis:6
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - default

  mysql: # root/rootroot
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default

  demo-homework:
    image: registry.hub.docker.com/taiwanbackendgroup/demo-homework:0.0.1-SNAPSHOT
    environment:
      - TZ=Asia/Taipei
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default: